### ISSUE TITLE
Getting Started Guide : Hello Triangle incorrect method args type

### ISSUE THREAD

**Issue by useCallback** [opentk/opentk.net#102]
## Description:
In the Getting started guide in the Hello Triangle section , there is an Incorrect arguments type for the `OnFramebufferResize` method

## Current content:
```cs       
protected override void OnFramebufferResize(ResizeEventArgs e)
{
    base.OnFramebufferResize(e);

    GL.Viewport(0, 0, e.Width, e.Height);
}
```

https://github.com/opentk/opentk.net/blob/dd939cffe4680dc396b28af2c4c5d58dc222658d/learn/chapter1/2-hello-triangle.md?plain=1#L104C1-L112C1

## Expected content:
```cs       
protected override void OnFramebufferResize(FramebufferResizeEventArgs e)
        {
            base.OnFramebufferResize(e);
            GL.Viewport(0, 0, e.Width, e.Height);

        }
```

**Comment by NogginBops** [comment]
Good catch! Must have missed that when I added that part to the tutorial.
Will fix this next time I work on the website.
