### ISSUE TITLE
Mistake in tutorial

### ISSUE THREAD

**Issue by AirborneDetergent** [opentk/opentk.net#86]
I was starting the tutorial and it noticed that at https://opentk.net/learn/chapter1/1-creating-a-window.html#creating-a-window-1, this code snippet is given.

```cs
// This line creates a new instance, and wraps the instance in a using statement so it's automatically disposed once we've exited the block.
using (Game game = new Game(800, 600, "LearnOpenTK"))
{
    //Run takes a double, which is how many frames per second it should strive to reach.
    //You can leave that out and it'll just update as fast as the hardware will allow it.
    game.Run(60.0);
}
```

In reality, game.Run() doesn't accept any arguments in OpenTK 4.7.5, so tutorial must be out of date. I made sure that I was on the 4 switch instead of the 3 switch. It's worth noting that the code-only tutorial on GitHub does not have this problem: https://github.com/opentk/LearnOpenTK/blob/master/Chapter1/1-CreatingAWindow/Program.cs

**Comment by NogginBops** [comment]
Just pushed a fix for this to the website.
