### ISSUE TITLE
Hello Triangle Tutorial broken link.

### ISSUE THREAD

**Issue by mattlongname** [opentk/opentk.net#90]
Towards the bottom of the ["Hello Triangle" page](https://opentk.net/learn/chapter1/2-hello-triangle.html?tabs=onload-opentk3%2Conrender-opentk3%2Cresize-opentk3#shaders) there is a **broken** link to the corresponding example repository page:
_"The source code for the complete program can be found here"_

It currently is:
```
https://github.com/opentk/LearnOpenTK/tree/master/Chapter%201/2%20-%20Hello%20Triangle`
```
It should be: 
```
https://github.com/opentk/LearnOpenTK/tree/master/Chapter1/2-HelloTriangle
```
without the `%20s` (spaces)

**Comment by NogginBops** [comment]
Fixed with 3ead62f
