### ISSUE TITLE
the tutorial for opentk doesn't mention anything about GLSL and compiling shaders and assumes the reader knows

### ISSUE THREAD

**Issue by Granolaa17** [opentk/opentk.net#94]

**Comment by NogginBops** [comment]
We do have a section about writing and compiling shaders: https://opentk.net/learn/chapter1/2-hello-triangle.html#shaders

**Comment by NogginBops** [comment]
Going to close this as I assume this isn't an issue any more. But if you think the issue has not been solved, feel free to reopen the issue.
