### ISSUE TITLE
The tutorial uses OnUpdateFrame which is obsolete

### ISSUE THREAD

**Issue by Martinecko30** [opentk/opentk.net#98]
--The tutorial uses OnUpdateFrame in https://opentk.net/learn/chapter1/9-camera.html#walk-around, also it's really hard to know where to put all the code shown before as in the repo it shows being used to render each frame but in tutorial it only needs to be assigned at OnLoad? It's hard to tell because it's not written in it.--

I am just dumb, ignore this

**Comment by NogginBops** [comment]
`OnUpdateFrame` is not deprecated?
